version: "3.9"

services:
  loki:
    ports:
      - "3100:3100"
    image: grafana/loki

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=cludus
      - GF_SECURITY_ADMIN_PASSWORD=cludus
    depends_on:
      - loki

  redis:
    image: redis

  identity:
    environment:
      JWT_SECRET_KEY: 1JK34H98DSFH3249DFH9234J0923J0FDH798G87342H98DFN90SAJ0M9AS2U3J8AJ09AS
      JWT_ISSUER: cludus-tests
      DB_HOSTNAME: roachdb
      DB_PORT: 26257
      DB_NAME: auth_db
      DB_USERNAME: root
      DB_PASSWORD:
      LOKI_URL: http://loki:3100
    ports:
      - "8090:8090"
    image: ghcr.io/cludus/identity-java:1.0.0
    depends_on:
      - roachdb
      - loki

  roachdb:
    image: cockroachdb/cockroach:latest
    environment:
      COCKROACH_DATABASE: auth_db
    command: start-single-node --insecure
    volumes:
      - "${PWD}/volumes/roach1:/cockroach/cockroach-data"