# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Release New Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be released
        required: true
        default: ''
      next_version:
        description: Next version to be released
        required: true
        default: ''

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - run: |
        git config --global user.email "admin@cludus.xyz"
        git config --global user.name "cludusadmin"
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.8.1
      with:
        arguments: release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.events.inputs.version }} -Prelease.newVersion=${{ github.events.inputs.next_version }}-SNAPSHOT
      env:
        GITHUB_ACTOR: gilbva
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
